name = "trip-expense-tracker"
type = "javascript"

account_id = "8cc45fdb94bd0ccd3e802620ef758da9"
workers_dev = true
compatibility_date = "2024-07-21"

kv_namespaces = [
  { binding = "TRIP_KV", id = "49db79caefc444288f1ba4e0083f400e" }
]
