name = "trip-expense-bot"
account_id = "8cc45fdb94bd0ccd3e802620ef758da9"
main = "worker.js"
type = "javascript"

kv_namespaces = [
  { binding = "KV_BINDING", id = "49db79caefc444288f1ba4e0083f400e" }
]
