name = "telegram-trip-expense-bot"
account_id = "8cc45fdb94bd0ccd3e802620ef758da9"
main = "worker.js"
type = "javascript"
compatibility_date = "2025-07-21"

kv_namespaces = [
  { binding = "KV_BINDING", id = "49db79caefc444288f1ba4e0083f400e" }
]

rules = [
  { type = "Text", globs = ["**/*.html"] }
]